<a href="https://colab.research.google.com/github/Katoshy/Data-Analysis-Projects/blob/main/AD_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Створення матриці 3х3

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Створення масиву типу з плаваючою точкою

In [ ]:
a=np.array([1, 2, 3, 4], dtype='float')
a

array([1., 2., 3., 4.])

Створення масиву від 0 до 17

In [ ]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

Створення масиву з одиницю (9 шт.) цілочисельного типу

In [ ]:
np.ones(9,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

Створення матриці з нулів 3х5 типу float

In [ ]:
np.zeros((3, 5), dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Створення масиву від 0 до 1 з рівномірно розподіленими значеннями (5шт.)

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Створення матриці 4х3 з значенням нормального розподілу (Гаусівського) при средньому значені μ = 1 стандартній девіації σ = 1

In [ ]:
np.random.normal(1,1,(4,3))

array([[ 2.02934593,  1.64917905,  2.16534482],
       [ 1.64164735, -0.16217045,  3.00350365],
       [ 0.83122233,  2.39609773,  1.50830864],
       [-0.5181565 ,  2.3153728 ,  0.82382369]])

Створення матриці 4х4 з цілочисельниз значень від 0 до 100 (виключно)

In [ ]:
np.random.randint(0, 100, (4, 4))

array([[81, 26, 91, 46],
       [22, 55, 57, 77],
       [55, 83, 85, 80],
       [24, 90, 89,  1]])

створення "пустого" масиву (забитого значенням що вже лежали у комірках пам'яті комп'ютера)

In [ ]:
np.empty(3,dtype='int')

array([4604930618986332160, 4604930618986332160,                   0])

створення масивів різними способами , та виведення їх вимірностей (к-сті вимірів)

In [ ]:
b=np.random.randint(0, 7, (4,4,3))
a=np.array([1, 2, 3, 4, 5, 6, 7], dtype='float')
b.ndim, a.ndim

(3, 1)

Виведення їх розмірностей по кожному з вимірів

In [ ]:
b.shape, a.shape

((4, 4, 3), (7,))

Кількість елементів кожного з масивів

In [ ]:
b.size, a.size

(48, 7)

In [ ]:
b.dtype, a.dtype

(dtype('int64'), dtype('float64'))

In [ ]:
b.nbytes, a.nbytes

(384, 40)

Розмір кожного елемента в байтах

In [ ]:
b.itemsize, a.itemsize 

(8, 8)

In [ ]:
a=np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
a[1],a[4],a[-3]

(1, 4, 4)

In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b[1,2],b[1,-2],b[1,1]

(array([3, 3, 2]), array([3, 3, 2]), array([2, 2, 3]))

In [ ]:
print(a[1::2])

[1 3 5]


In [ ]:
print(a)
a[0:4:1], a[5::-2]

[0 1 2 3 4 5 6]


(array([0, 1, 2, 3]), array([5, 3, 1]))

In [ ]:
c=b[:2,:2].copy()
c

array([[1, 2],
       [4, 5]])

In [ ]:
c[0,0]=17
print(c)

[[17  2]
 [ 4  5]]


In [ ]:
a=np.ones(4)
a+3, a*2, (3*a+1)**2,a/2,-a


(array([4., 4., 4., 4.]),
 array([2., 2., 2., 2.]),
 array([16., 16., 16., 16.]),
 array([0.5, 0.5, 0.5, 0.5]),
 array([-1., -1., -1., -1.]))

In [ ]:
print(a)
np.multiply.reduce(a)

[1. 2. 3. 4. 5. 6. 7.]


5040.0

In [ ]:
np.add.accumulate(a)

array([ 1.,  3.,  6., 10., 15., 21., 28.])

In [ ]:
а = np.arange(1, 10)
np.multiply.outer(а, а)


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

Зчитування файлу з таблицею даних за допомогою Pandas , та виведення колонки "ширина пелюстки"

In [ ]:
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/iris.csv')
petal = np.array(data['petal_width'])
petal

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8])

In [ ]:
petal.max()

2.5

In [ ]:
petal.min()

0.1

In [ ]:
petal.mean()

1.1986666666666668

In [ ]:
np.median(petal)

1.3

In [ ]:
np.var(petal)

0.5785315555555555

In [ ]:
np.std(petal)
#Функція std() в середньоквадратичне (стандартне) відхилення

0.7606126185881716

In [ ]:
np.percentile(petal,25)

0.3

In [ ]:
np.percentile(petal,75)

1.8